// get sports
export const GET_FEATURES = "GET_FEATURES";
export const GET_FEATURES_SUCCESS = "GET_FEATURES_SUCCESS";
export const GET_FEATURES_FAILED = "GET_FEATURES_FAILED";

// add feature
export const ADD_FEATURE = "ADD_FEATURE";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAILED = "ADD_FEATURE_FAILED";

// update feature
export const UPDATE_FEATURE = "UPDATE_FEATURE";
export const UPDATE_FEATURE_SUCCESS = "UPDATE_FEATURE_SUCCESS";
export const UPDATE_FEATURE_FAILED = "UPDATE_FEATURE_FAILED";
