// get facilities
export const GET_FACILITIES = "GET_FACILITIES";
export const GET_FACILITIES_SUCCESS = "GET_FACILITIES_SUCCESS";
export const GET_FACILITIES_FAILED = "GET_FACILITIES_FAILED";

// get added facilities
export const GET_ADDED_FACILITIES = "GET_ADDED_FACILITIES";
export const GET_ADDED_FACILITIES_SUCCESS = "GET_ADDED_FACILITIES_SUCCESS";
export const GET_ADDED_FACILITIES_FAILED = "GET_ADD_FACILITIES_FAILED";

// get facility by id
export const GET_FACILITY_BY_ID = "GET_FACILITY_BY_ID";
export const GET_FACILITY_BY_ID_SUCCESS = "GET_FACILITY_BY_ID_SUCCESS";
export const GET_FACILITY_BY_ID_FAILED = "GET_FACILITY_BY_ID_FAILED";

// get facility by name
export const GET_FACILITY_BY_NAME = "GET_FACILITY_BY_NAME";
export const GET_FACILITY_BY_NAME_SUCCESS = "GET_FACILITY_BY_NAME_SUCCESS";
export const GET_FACILITY_BY_NAME_FAILED = "GET_FACILITY_BY_NAME_FAILED";

// get facility by sport
export const GET_FACILITIES_BY_SPORT_ID = "GET_FACILITIES_BY_SPORT_ID";
export const GET_FACILITIES_BY_SPORT_ID_SUCCESS =
  "GET_FACILITIES_BY_SPORT_ID_SUCCESS";
export const GET_FACILITIES_BY_SPORT_ID_FAILED =
  "GET_FACILITIES_BY_SPORT_ID_FAILED";

// search facilities
export const SEARCH_FACILITIES = "SEARCH_FACILITIES";
export const SEARCH_FACILITIES_SUCCESS = "SEARCH_FACILITIES_SUCCESS";
export const SEARCH_FACILITIES_FAILED = "SEARCH_FACILITIES_FAILED";

// delete facility
export const DELETE_FACILITY = "DELETE_FACILITY";
export const DELETE_FACILITY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const DELETE_FACILITY_FAILED = "DELETE_FACILITY_FAILED";
