// get courts
export const GET_COURTS = "GET_COURTS";
export const GET_COURTS_SUCCESS = "GET_COURTS_SUCCESS";
export const GET_COURTS_FAILED = "GET_COURTS_FAILED";

// get courts by facility
export const GET_COURTS_BY_FACILITY = "GET_COURTS_BY_FACILITY";
export const GET_COURTS_BY_FACILITY_SUCCESS = "GET_COURTS_BY_FACILITY_SUCCESS";
export const GET_COURTS_BY_FACILITY_FAILED = "GET_COURTS_BY_FACILITY_FAILED";

// get courts by facility and sport
export const GET_COURTS_BY_FACILITY_AND_SPORTS =
  "GET_COURTS_BY_FACILITY_AND_SPORTS";
export const GET_COURTS_BY_FACILITY_AND_SPORTS_SUCCESS =
  "GET_COURTS_BY_FACILITY_AND_SPORTS_SUCCESS";
export const GET_COURTS_BY_FACILITY_AND_SPORTS_FAILED =
  "GET_COURTS_BY_FACILITY_AND_SPORTS_FAILED";

// delete court
export const DELETE_COURT = "DELETE_COURT";
export const DELETE_COURT_SUCCESS = "DELETE_COURT_SUCCESS";
export const DELETE_COURT_FAILED = "DELETE_COURT_FAILED";
